import 'package:kazakh_worship/models/song.dart';
import 'package:kazakh_worship/services/lyrics.dart';

final songList = [
  Song(id: '27', title: 'Адамдар, ойланындар', lyrics: adamdarOilanindar),
  Song(id: '96', title: 'Айқыш ағашта қиналдың', lyrics: aikish),
  Song(id: '102', title: 'Алғыс Саған, жалғыз Саған', lyrics: algisSagan),
  Song(id: '36', title: 'Арайлап атты таңдарым', lyrics: arailap),
  Song(id: '31', title: 'Арайымен атқан күннің нұр кү', lyrics: araimen),
  Song(id: '105', title: 'Аспанда жарық ай', lyrics: aspanda),
  Song(id: '8', title: 'Аспанда таңғы жұлдыз туған кезде', lyrics: tangiJuldiz),
  Song(id: '112', title: 'Атың мадақталсын', lyrics: atin),
  Song(id: '98', title: 'Әлемнің бәрін Құдай жаратқан', lyrics: alemnin),
  Song(id: '3', title: 'Бəрі тыныш, əлем ұйықтап жатқанда', lyrics: tinish),
  Song(id: '132', title: 'Балық - суда', lyrics: balyk),
  Song(
      id: '106',
      title: 'Бар әлемді жаратқан Құдіретті Құдай',
      lyrics: barAlemdi),
  Song(id: '94', title: 'Барлық аспан', lyrics: barlykAspan),
  Song(id: '15', title: 'Бауырым, айқыш ағашқа қара', lyrics: bauirim),
  Song(id: '130', title: 'Бәрің, бәрің келіңдер', lyrics: barin),
  Song(id: '59', title: 'Бейбітшілік орнасын елімізде', lyrics: beybitshilik),
  Song(
      id: '122',
      title: 'Бізге бұл күнді, Құдай жаратқан',
      lyrics: bizgeBulKundi),
  Song(id: '134', title: 'Бурхан дэлхийг үнэхээр', lyrics: burhan),
  Song(id: '7', title: 'Бүгін міне, қуанышта шек болмас', lyrics: buginMine),
  Song(id: '127', title: 'Бүкіл әлем Құдайдың қолында', lyrics: bukil),
  Song(id: '99', title: 'Бүкіл жаныммен', lyrics: bukilJanimmen),
  Song(id: '104', title: 'Бұл əлемнің бастамасы', lyrics: bulAlemnin),
  Song(id: '30', title: 'Бұл өмірден өтеді екен данал', lyrics: bulOmirden),
  Song(id: '45', title: 'Далама көз салсам', lyrics: dalama),
  Song(id: '74', title: 'Дүние бастан-аяқ адасқан', lyrics: duniye),
  Song(id: '50', title: 'Дүниені бір сөзіңмен жараттың', lyrics: duniyeni),
  Song(id: '78', title: 'Егер жүрсем өлімге', lyrics: eger),
  Song(id: '18', title: 'Екі мың жылдай ертерек', lyrics: eki),
  Song(id: '72', title: 'Жан Әкем! Мейірімді Әкем!', lyrics: janAkem),
  Song(id: '4', title: 'Жарқырап кетті айнала', lyrics: jarkirap),
  Song(id: '54', title: 'Жасыл жайлауға', lyrics: jasyl),
  Song(id: '129', title: 'Жедел хабар келеді', lyrics: jedel),
  Song(id: '68', title: 'Жетеле бізді, жетеле көкке', lyrics: jetele),
  Song(id: '66', title: 'Жетеле мені', lyrics: jeteleMeni),
  Song(id: '11', title: 'Жол Ғолғофаға', lyrics: jolGolgofaga),
  Song(id: '61', title: 'Жолымдағы жарық жұлдыздай', lyrics: jolimdagi),
  Song(id: '126', title: 'Жүрегімді өзгерт, О, Тәңір Ием', lyrics: juregimdi),
  Song(id: '58', title: 'Жүрегіме жүз қарап', lyrics: juregime),
  Song(id: '43', title: 'Жүрегіммен Тәңіріме мен шаттанам', lyrics: juregimmen),
  Song(id: '48', title: 'Жұлдыздар жарқырап жанғанда', lyrics: juldizdar),
  Song(id: '5', title: 'Жым-жырт түн, ғажап түн!', lyrics: jimJirtTun),
  Song(id: '28', title: 'Жыр болып бізге ашылшы Тəңір', lyrics: jirBolip),
  Song(id: '110', title: 'Иемізді мадақтаңдар', lyrics: iemizdi),
  Song(id: '128', title: 'Иемізді мадақтаңдар!', lyrics: iemizdi),
  Song(id: '101', title: 'Иса бізді сүйеді, аллелуйя!', lyrics: isaBizdi),
  Song(id: '118', title: 'Иса біздің берік панамыз', lyrics: isaBizdin),
  Song(id: '52', title: 'Иса деймін ойыммен', lyrics: isaDeymin),
  Song(id: '21', title: 'Иса мені қабылда', lyrics: isaMeni),
  Song(id: '81', title: 'Иса мені сүйеді', lyrics: isaMeniSuyedi),
  Song(id: '120', title: 'Иса Сен біздің арамыздасың', lyrics: isaSen),
  Song(id: '83', title: 'Иса сені сүйеді ей, бауырым!', lyrics: isaSeni),
  Song(id: '111', title: 'Иса, жалғыз Сен - Иса!', lyrics: isaJalgyzSen),
  Song(id: '93', title: 'Иса, толып тұр менің жүрегімде', lyrics: isaTolip),
  Song(id: '136', title: 'Исаиа 53', lyrics: isaia),
  Song(id: '1', title: 'Кел, кел бізге Имануил', lyrics: kelKel),
  Song(id: '109', title: 'Кел, Құдайды мадақтауға', lyrics: kel),
  Song(id: '67', title: 'Келгейсің, келгейсің', lyrics: kelgeysin),
  Song(id: '123', title: 'Келемін Саған', lyrics: kelemin),
  Song(id: '44', title: 'Киелі Рух көз бердің', lyrics: kiely),
  Song(id: '69', title: 'Кіммін мен, бүкіл әлем патшасы', lyrics: kimmimMen),
  Song(id: '80', title: 'Көк, аспан күтеді мені', lyrics: kokAspan),
  Song(id: '79', title: 'Көктегі Əкемізге болсын мадақ', lyrics: koktegi),
  Song(id: '19', title: 'Көктем келді', lyrics: koktem),
  Song(id: '57', title: 'Күйе басқан шырағыңның', lyrics: kuye),
  Song(id: '53', title: 'Күлімдеп күннің көзі', lyrics: kulimdep),
  Song(id: '77', title: 'Қайғы тартып қиналғанда', lyrics: kaygi),
  Song(id: '65', title: 'Қалдым мен тоғай ішінде', lyrics: kaldim),
  Song(id: '125', title: 'Қандай бақыт!', lyrics: kanday),
  Song(id: '29', title: 'Қиналсам да бұл өмірде', lyrics: kinalsam),
  Song(id: '71', title: 'Қолымды көкке', lyrics: kolimdi),
  Song(id: '131', title: 'Қорғаушымыз Құдайды', lyrics: korgaushimiz),
  Song(id: '2', title: 'Қуаныңдар', lyrics: kuanindar),
  Song(id: '37', title: 'Қуаныңдар достарым', lyrics: kuanindarDostarim),
  Song(id: '40', title: 'Құдай біздің Әкеміз', lyrics: kudayBizdinAkemiz),
  Song(id: '133', title: 'Құдай мені жаратты', lyrics: kudayMeniJaratti),
  Song(id: '116', title: 'Құдай сені тастамайды ешқашан', lyrics: kudaySeni),
  Song(id: '42', title: 'Құдай сізді әуел баста', lyrics: kudaySizdi),
  Song(id: '124', title: 'Құдай сондай жақсы', lyrics: kudaySonday),
  Song(id: '26', title: 'Құдай сонша жақсы көрді', lyrics: kudaySonsha),
  Song(
      id: '34', title: 'Құдайдың Сөзімен өмірім өзгерді', lyrics: kudaydinSozi),
  Song(id: '39', title: 'Құдайсыз өмір – бақытсыз өмір', lyrics: kudaysiz),
  Song(id: '76', title: 'Құрбан еттің біз үшін', lyrics: kurban),
  Song(id: '87', title: 'Құрметтеймін Сені балаңдай', lyrics: kurmetteymin),
  Song(id: '107', title: 'Құтқардың мені Иса', lyrics: kutkardin),
  Song(id: '73', title: 'Мəңгілік Сенімен', lyrics: mangilik),
  Song(id: '86', title: 'Мадақтаймын Сені', lyrics: madaktaymin),
  Song(id: '16', title: 'Мен Саған өлең айтам', lyrics: menSagan),
  Song(id: '56', title: 'Мен Сенің алдыңа келіп тұрмын', lyrics: menSenin),
  Song(id: '100', title: 'Мен Тәңірге әрқашан', lyrics: menTanirge),
  Song(id: '47', title: 'Мен тоқтап, біраз көз салсам', lyrics: menToktap),
  Song(id: '119', title: 'Менің аяулы арманым', lyrics: menin),
  Song(id: '62', title: 'Менің Ұлы Ұстазым', lyrics: meninUlly),
  Song(id: '14', title: 'Міне бүгін, келді уақыт Саған', lyrics: mineBugin),
  Song(id: '55', title: 'Мөлдір аққан судай өмір', lyrics: moldir),
  Song(id: '121', title: 'Мұңға батсам жүрегім мұздап', lyrics: munga),
  Song(id: '60', title: 'Нұрсың Сен', lyrics: nursin),
  Song(id: '20', title: 'О, аспандағы Əкеміз', lyrics: aspandagi),
  Song(id: '89', title: 'О, Құдай Ием', lyrics: kudayIem),
  Song(id: '92', title: 'О, Құдай қарашы маған', lyrics: kudayKarashi),
  Song(id: '41', title: 'О, Құдай Сен деген жақсы', lyrics: kudaySen),
  Song(id: '108', title: 'Ол мадақталсын', lyrics: olMadaqtalsin),
  Song(id: '38', title: 'Өмірдің мақсаты не деп ойлайсың?', lyrics: omirdin),
  Song(id: '70', title: 'Өмірімді Саған арнадым', lyrics: omirimdi),
  Song(id: '103', title: 'Пәк жүрек', lyrics: pak),
  Song(id: '114', title: 'Рахмет Саған Құдай', lyrics: rahmet),
  Song(id: '63', title: 'Сен қастерлісің', lyrics: senKasterlisin),
  Song(id: '49', title: 'Сен, Тəңірім', lyrics: senTanirim),
  Song(id: '51', title: 'Сенемін мен сенемін ұлы Құдайыма', lyrics: seneminMen),
  Song(id: '23', title: 'Сиын қуанышты кезіңде', lyrics: siyin),
  Song(id: '24', title: 'Cиынғанда Құдайменен сөйле', lyrics: siyingan),
  Song(id: '25', title: 'Сол бір үйде', lyrics: solBir),
  Song(id: '33', title: 'Сөзіңді алдым қолыма', lyrics: sozindi),
  Song(id: '84', title: 'Сүйіспеншілік', lyrics: suispenshilik),
  Song(id: '85', title: 'Сүйіспеншілікпен əндетіп', lyrics: suispenshilikpen),
  Song(id: '22', title: 'Тəңір Ием арамызда', lyrics: tanirIem),
  Song(id: '97', title: 'Тəңірдің Рухы мені толтырғанда', lyrics: tanirdinRuhi),
  Song(id: '90', title: 'Тəңірімнің аты қамал сияқты', lyrics: tanirimninAti),
  Song(id: '46', title: 'Тазалап мені күнəдан', lyrics: tazalap),
  Song(id: '88', title: 'Таң атқанда оянып, Сені шақы', lyrics: tanAtkanda),
  Song(id: '64', title: 'Тәңір жолыма жарық шашып', lyrics: tanirJolima),
  Song(id: '17', title: 'Тәңір Иса тірілді, аллелуйя!', lyrics: tanirIsa),
  Song(
      id: '6',
      title: 'Тәңір Өзі көктен түсіп, жер бетіне келеді',
      lyrics: tanirOzi),
  Song(
      id: '113', title: 'Тәңірді мадақта жан-дүнием!', lyrics: teanirdiMadaqta),
  Song(id: '35', title: 'Тәңірім алдыңда тұрамын', lyrics: tanirimAldinda),
  Song(id: '75', title: 'Тәңірім менің Бағушым', lyrics: tanirimMenin),
  Song(id: '13', title: 'Түнгі дала тұрды тұнжырап', lyrics: tungi),
  Song(id: '9', title: 'Түнгі далаға қар жауып', lyrics: tungiDalaga),
  Song(id: '117', title: 'Түнекте мен жалғыз жүрдім', lyrics: tunekte),
  Song(id: '32', title: 'Тыңдаумен жүріп Өзінді', lyrics: tindaumen),
  Song(id: '10', title: 'Уақыт келді', lyrics: uaqit),
  Song(id: '95', title: 'Шаттанамын Ұлы Құдай жүрегі', lyrics: shattanamin),
  Song(id: '91', title: 'Эвейну шалом алейхем', lyrics: eveynu),
];
