import 'package:kazakh_worship/models/song.dart';
import 'package:kazakh_worship/services/lyrics.dart';

final songList = [
      Song(id: '27', title: 'Адамдар, ойланындар', lyrics: adamdarOilanindar),
      Song(id: '96', title: 'Айқыш ағашта қиналдың', lyrics: aikish),
      Song(id: '102', title: 'Алғыс Саған, жалғыз Саған', lyrics: null),
      Song(id: '36', title: 'Арайлап атты таңдарым', lyrics: null),
      Song(id: '31', title: 'Арайымен атқан күннің нұр кү', lyrics: null),
      Song(id: '105', title: 'Аспанда жарық ай', lyrics: null),
      Song(id: '8', title: 'Аспанда таңғы жұлдыз туған кезде', lyrics: null),
      Song(id: '112', title: 'Атың мадақталсын', lyrics: null),
      Song(id: '98', title: 'Әлемнің бәрін Құдай жаратқан', lyrics: null),
      Song(id: '3', title: 'Бəрі тыныш, əлем ұйықтап жатқанда', lyrics: null),
      Song(id: '132', title: 'Балық - суда', lyrics: null),
      Song(
          id: '106',
          title: 'Бар әлемді жаратқан Құдіретті Құдай',
          lyrics: null),
      Song(id: '94', title: 'Барлық аспан', lyrics: null),
      Song(id: '15', title: 'Бауырым, айқыш ағашқа қара', lyrics: null),
      Song(id: '130', title: 'Бәрің, бәрің келіңдер', lyrics: null),
      Song(id: '59', title: 'Бейбітшілік орнасын елімізде', lyrics: null),
      Song(id: '122', title: 'Бізге бұл күнді, Құдай жаратқан', lyrics: null),
      Song(id: '134', title: 'Бурхан дэлхийг үнэхээр', lyrics: null),
      Song(id: '7', title: 'Бүгін міне, қуанышта шек болмас', lyrics: null),
      Song(id: '127', title: 'Бүкіл әлем Құдайдың қолында', lyrics: null),
      Song(id: '99', title: 'Бүкіл жаныммен', lyrics: null),
      Song(id: '104', title: 'Бұл əлемнің бастамасы', lyrics: null),
      Song(id: '30', title: 'Бұл өмірден өтеді екен данал', lyrics: null),
      Song(id: '45', title: 'Далама көз салсам', lyrics: null),
      Song(id: '74', title: 'Дүние бастан-аяқ адасқан', lyrics: null),
      Song(id: '50', title: 'Дүниені бір сөзіңмен жараттың', lyrics: null),
      Song(id: '78', title: 'Егер жүрсем өлімге', lyrics: null),
      Song(id: '18', title: 'Екі мың жылдай ертерек', lyrics: null),
      Song(id: '72', title: 'Жан Әкем! Мейірімді Әкем!', lyrics: null),
      Song(id: '4', title: 'Жарқырап кетті айнала', lyrics: null),
      Song(id: '54', title: 'Жасыл жайлауға', lyrics: null),
      Song(id: '129', title: 'Жедел хабар келеді', lyrics: null),
      Song(id: '68', title: 'Жетеле бізді, жетеле көкке', lyrics: null),
      Song(id: '66', title: 'Жетеле мені', lyrics: null),
      Song(id: '11', title: 'Жол Ғолғофаға', lyrics: null),
      Song(id: '61', title: 'Жолымдағы жарық жұлдыздай', lyrics: null),
      Song(id: '126', title: 'Жүрегімді өзгерт, О, Тәңір Ием', lyrics: null),
      Song(id: '58', title: 'Жүрегіме жүз қарап', lyrics: null),
      Song(id: '43', title: 'Жүрегіммен Тәңіріме мен шаттанам', lyrics: null),
      Song(id: '48', title: 'Жұлдыздар жарқырап жанғанда', lyrics: null),
      Song(id: '5', title: 'Жым-жырт түн, ғажап түн!', lyrics: null),
      Song(id: '28', title: 'Жыр болып бізге ашылшы Тəңір', lyrics: null),
      Song(id: '110', title: 'Иемізді мадақтаңдар', lyrics: null),
      Song(id: '128', title: 'Иемізді мадақтаңдар!', lyrics: null),
      Song(id: '101', title: 'Иса бізді сүйеді, аллелуйя!', lyrics: null),
      Song(id: '118', title: 'Иса біздің берік панамыз', lyrics: null),
      Song(id: '52', title: 'Иса деймін ойыммен', lyrics: null),
      Song(id: '21', title: 'Иса мені қабылда', lyrics: null),
      Song(id: '81', title: 'Иса мені сүйеді', lyrics: null),
      Song(id: '120', title: 'Иса Сен біздің арамыздасың', lyrics: null),
      Song(id: '83', title: 'Иса сені сүйеді ей, бауырым!', lyrics: null),
      Song(id: '111', title: 'Иса, жалғыз Сен - Иса!', lyrics: null),
      Song(id: '93', title: 'Иса, толып тұр менің жүрегімде', lyrics: null),
      Song(id: '136', title: 'Исаиа 53', lyrics: null),
      Song(id: '1', title: 'Кел, кел бізге Имануил', lyrics: null),
      Song(id: '109', title: 'Кел, Құдайды мадақтауға', lyrics: null),
      Song(id: '67', title: 'Келгейсің, келгейсің', lyrics: null),
      Song(id: '123', title: 'Келемін Саған', lyrics: null),
      Song(id: '44', title: 'Киелі Рух көз бердің', lyrics: null),
      Song(id: '69', title: 'Кіммін мен, бүкіл әлем патшасы', lyrics: null),
      Song(id: '80', title: 'Көк, аспан күтеді мені', lyrics: null),
      Song(id: '79', title: 'Көктегі Əкемізге болсын мадақ', lyrics: null),
      Song(id: '19', title: 'Көктем келді', lyrics: null),
      Song(id: '57', title: 'Күйе басқан шырағыңның', lyrics: null),
      Song(id: '53', title: 'Күлімдеп күннің көзі', lyrics: null),
      Song(id: '77', title: 'Қайғы тартып қиналғанда', lyrics: null),
      Song(id: '65', title: 'Қалдым мен тоғай ішінде', lyrics: null),
      Song(id: '125', title: 'Қандай бақыт!', lyrics: null),
      Song(id: '29', title: 'Қиналсам да бұл өмірде', lyrics: null),
      Song(id: '71', title: 'Қолымды көкке', lyrics: null),
      Song(id: '131', title: 'Қорғаушымыз Құдайды', lyrics: null),
      Song(id: '2', title: 'Қуаныңдар', lyrics: null),
      Song(id: '37', title: 'Қуаныңдар достарым', lyrics: null),
      Song(id: '40', title: 'Құдай біздің Әкеміз', lyrics: null),
      Song(id: '133', title: 'Құдай мені жаратты', lyrics: null),
      Song(id: '116', title: 'Құдай сені тастамайды ешқашан', lyrics: null),
      Song(id: '42', title: 'Құдай сізді әуел баста', lyrics: null),
      Song(id: '124', title: 'Құдай сондай жақсы', lyrics: null),
      Song(id: '26', title: 'Құдай сонша жақсы көрді', lyrics: null),
      Song(id: '34', title: 'Құдайдың Сөзімен өмірім өзгерді', lyrics: null),
      Song(id: '39', title: 'Құдайсыз өмір – бақытсыз өмір', lyrics: null),
      Song(id: '76', title: 'Құрбан еттің біз үшін', lyrics: null),
      Song(id: '87', title: 'Құрметтеймін Сені балаңдай', lyrics: null),
      Song(id: '107', title: 'Құтқардың мені Иса', lyrics: null),
      Song(id: '73', title: 'Мəңгілік Сенімен', lyrics: null),
      Song(id: '86', title: 'Мадақтаймын Сені', lyrics: null),
      Song(id: '16', title: 'Мен Саған өлең айтам', lyrics: null),
      Song(id: '56', title: 'Мен Сенің алдыңа келіп тұрмын', lyrics: null),
      Song(id: '100', title: 'Мен Тәңірге әрқашан', lyrics: null),
      Song(id: '47', title: 'Мен тоқтап, біраз көз салсам', lyrics: null),
      Song(id: '119', title: 'Менің аяулы арманым', lyrics: null),
      Song(id: '62', title: 'Менің Ұлы Ұстазым', lyrics: null),
      Song(id: '14', title: 'Міне бүгін, келді уақыт Саған', lyrics: null),
      Song(id: '55', title: 'Мөлдір аққан судай өмір', lyrics: null),
      Song(id: '121', title: 'Мұңға батсам жүрегім мұздап', lyrics: null),
      Song(id: '60', title: 'Нұрсың Сен', lyrics: null),
      Song(id: '20', title: 'О, аспандағы Əкеміз', lyrics: null),
      Song(id: '89', title: 'О, Құдай Ием', lyrics: null),
      Song(id: '92', title: 'О, Құдай қарашы маған', lyrics: null),
      Song(id: '41', title: 'О, Құдай Сен деген жақсы', lyrics: null),
      Song(id: '108', title: 'Ол мадақталсын', lyrics: null),
      Song(id: '38', title: 'Өмірдің мақсаты не деп ойлайсың?', lyrics: null),
      Song(id: '70', title: 'Өмірімді Саған арнадым', lyrics: null),
      Song(id: '103', title: 'Пәк жүрек', lyrics: null),
      Song(id: '114', title: 'Рахмет Саған Құдай', lyrics: null),
      Song(id: '63', title: 'Сен қастерлісің', lyrics: null),
      Song(id: '49', title: 'Сен, Тəңірім', lyrics: null),
      Song(id: '51', title: 'Сенемін мен сенемін ұлы Құдайыма', lyrics: null),
      Song(id: '23', title: 'Сиын қуанышты кезіңде', lyrics: null),
      Song(id: '24', title: 'Cиынғанда Құдайменен сөйле', lyrics: null),
      Song(id: '25', title: 'Сол бір үйде', lyrics: null),
      Song(id: '33', title: 'Сөзіңді алдым қолыма', lyrics: null),
      Song(id: '84', title: 'Сүйіспеншілік', lyrics: null),
      Song(id: '85', title: 'Сүйіспеншілікпен əндетіп', lyrics: null),
      Song(id: '22', title: 'Тəңір Ием арамызда', lyrics: null),
      Song(id: '97', title: 'Тəңірдің Рухы мені толтырғанда', lyrics: null),
      Song(id: '90', title: 'Тəңірімнің аты қамал сияқты', lyrics: null),
      Song(id: '46', title: 'Тазалап мені күнəдан', lyrics: null),
      Song(id: '88', title: 'Таң атқанда оянып, Сені шақы', lyrics: null),
      Song(id: '64', title: 'Тәңір жолыма жарық шашып', lyrics: null),
      Song(id: '17', title: 'Тәңір Иса тірілді, аллелуйя!', lyrics: null),
      Song(
          id: '6',
          title: 'Тәңір Өзі көктен түсіп, жер бетіне келеді',
          lyrics: null),
      Song(id: '113', title: 'Тәңірді мадақта жан-дүнием!', lyrics: null),
      Song(id: '35', title: 'Тәңірім алдыңда тұрамын', lyrics: null),
      Song(id: '75', title: 'Тәңірім менің Бағушым', lyrics: null),
      Song(id: '13', title: 'Түнгі дала тұрды тұнжырап', lyrics: null),
      Song(id: '9', title: 'Түнгі далаға қар жауып', lyrics: null),
      Song(id: '117', title: 'Түнекте мен жалғыз жүрдім', lyrics: null),
      Song(id: '32', title: 'Тыңдаумен жүріп Өзінді', lyrics: null),
      Song(id: '10', title: 'Уақыт келді', lyrics: null),
      Song(id: '95', title: 'Шаттанамын Ұлы Құдай жүрегі', lyrics: null),
      Song(id: '91', title: 'Эвейну шалом алейхем', lyrics: null),
    ];